# Generated by Django 5.0.4 on 2024-07-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreading',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='eis.counter'),
        ),
        migrations.AlterField(
            model_name='counterreading',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
