# Generated by Django 5.0.4 on 2024-07-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0002_alter_counterreading_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=11)),
                ('date', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_processes', to='eis.house')),
            ],
            options={
                'unique_together': {('house', 'date')},
            },
        ),
    ]
